language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker compose .
  - docker tag simple-node noursayed/simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push noursayed/udagram-frontend
  - docker push noursayed/udagram-api-user-v7
  - docker push noursayed/udagram-api-feed-v7
  - docker push noursayed/reverseproxy