language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed noursayed/udagram-api-feed:v10
  - docker tag udagram-api-user noursayed/udagram-api-user:v10
  - docker tag udagram-frontend noursayed/udagram-frontend:v10
  - docker tag udagram-reverseproxy noursayed/udagram-reverseproxy:v10

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push noursayed/udagram-frontend:v10
  - docker push noursayed/udagram-api-user:v10
  - docker push noursayed/udagram-api-feed:v10
  - docker push noursayed/udagram-reverseproxy:v10
