apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-app
  labels:
    app: feed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-app
  template:
    metadata:
      labels:
        app: feed-app
    spec:
      containers:
      - name: feed-app
        image: noursayed/udagram-api-feed:new      
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "400m"
 
